############# Portuguese navigation ##############

# main menu
[[main]]
name = "Início"
pageRef = "/pt-br/"
weight = 1

[[main]]
name = "Blog"
pageRef = "/blog/"
weight = 2

[[main]]
name = "Autores"
pageRef = "/authors/"
weight = 3

# footer menu
[[footer]]
name = "Política de privacidade"
pageRef = "/privacy-policy/"
weight = 1

[[footer]]
name = "Autores"
pageRef = "/authors/"
weight = 2
